r"""Regression test for Bug #20: _is_preserved_turn and _check_report_has_user_request
must detect the actual heading format `## User Request` (not the buggy bullet format).

This test verifies the fix applied to both:
1. SessionService._is_preserved_turn (line 293)
2. SessionPruningService._check_report_has_user_request (line 276)

The bug: The detection regex was `r"^- \*\*User Request:\*\*"` (bullet format) but the
template outputs `## User Request` (heading format). Hence detection always returned False.
"""

import re


# ---------------------------------------------------------------------------
# Simulate the exact detection methods from both services to test in isolation
# ---------------------------------------------------------------------------


def _simulate_buggy_detection(content: str) -> bool:
    """Current buggy regex (bullet format)."""
    return bool(re.search(r"^- \*\*User Request:\*\*", content, re.MULTILINE))


def _simulate_fixed_detection(content: str) -> bool:
    """Fixed regex (heading format matching actual template output)."""
    return bool(re.search(r"^## User Request", content, re.MULTILINE))


# ---------------------------------------------------------------------------
# Test data: realistic report content as generated by execution_report.md.j2
# ---------------------------------------------------------------------------

REPORT_WITH_USER_REQUEST = """# Execution Report: Test
- **Overall Status:** SUCCESS
- **Execution Start Time:** 2026-06-09T12:00:00+00:00
- **Execution End Time:** 2026-06-09T12:00:10+00:00

## User Request
```text
I want to add more features
```
"""

REPORT_WITHOUT_USER_REQUEST = """# Execution Report: Test
- **Overall Status:** SUCCESS
- **Execution Start Time:** 2026-06-09T12:00:00+00:00
- **Execution End Time:** 2026-06-09T12:00:10+00:00

## Action Log
### `READ`: [test.py](/test.py)
- **Status:** SUCCESS
"""

REPORT_WITH_BULLET_ASSUMPTION = """# Execution Report: Test
- **Overall Status:** SUCCESS
- **User Request:** fix the bug
"""


# ---------------------------------------------------------------------------
# Tests for _is_preserved_turn (SessionService) simulation
# ---------------------------------------------------------------------------


class TestSessionServiceIsPreservedTurnDetection:
    """Tests the detection logic that SessionService._is_preserved_turn uses."""

    def test_buggy_detection_fails_on_heading_format(self):
        """Buggy regex should NOT detect `## User Request` heading format."""
        assert _simulate_buggy_detection(REPORT_WITH_USER_REQUEST) is False, (
            "Buggy regex incorrectly matches heading format"
        )

    def test_fixed_detection_catches_heading_format(self):
        """Fixed regex SHOULD detect `## User Request` heading format."""
        assert _simulate_fixed_detection(REPORT_WITH_USER_REQUEST) is True, (
            "Fixed regex failed to detect heading format"
        )

    def test_no_false_positive_without_user_request(self):
        """Both regexes should return False when no user request marker present."""
        assert _simulate_buggy_detection(REPORT_WITHOUT_USER_REQUEST) is False
        assert _simulate_fixed_detection(REPORT_WITHOUT_USER_REQUEST) is False

    def test_buggy_detection_still_matches_bullet_format(self):
        """Buggy regex still matches bullet format (but template never outputs it)."""
        assert _simulate_buggy_detection(REPORT_WITH_BULLET_ASSUMPTION) is True

    def test_fixed_detection_does_not_match_bullet_format(self):
        """Fixed regex should NOT match bullet format (since template never outputs it)."""
        assert _simulate_fixed_detection(REPORT_WITH_BULLET_ASSUMPTION) is False


# ---------------------------------------------------------------------------
# Tests for _check_report_has_user_request (SessionPruningService)
# ---------------------------------------------------------------------------
